INSERT INTO verbete(id, verbete, pessoa_id) VALUES
    (1, 'A contento', 1),
    (2, 'Abertura de falência', 1),
    (3, 'Abolitio criminis', 2),
    (4, 'Ab-rogação', 2),
    (5, 'Abuso de autoridade', 2),
    (6, 'Abuso de poder', 1),
    (7, 'Ação', 1),
    (8, 'Ação cautelar', 1),
    (9, 'Ação cível originária', 1),
    (10, 'Ação civil pública', 1),
    (11, 'Ação de execução', 1),
    (12, 'Ação de improbidade administrativa', 1),
    (13, 'Ação de jurisdição voluntária', 1),
    (14, 'Ação de reintegração de posse', 1),
    (15, 'Ação declaratória', 1),
    (16, 'Ação Declaratória de Constitucionalidade (ADC)', 1),
    (17, 'Ação Direta de Inconstitucionalidade (ADI)', 1),
    (18, 'Ação penal', 1),
    (19, 'Ação popular', 1),
    (20, 'Ação regressiva', 1),
    (21, 'Ação rescisória', 1),
    (22, 'Acautelar', 1),
    (23, 'Acórdão', 1),
    (24, 'Ad argumentandum tantum', 1),
    (25, 'Ad cautelam', 1),
    (26, 'Ad hoc', 1),
    (27, 'Ad nutum', 1),
    (28, 'Ad referendum', 1),
    (29, 'ADCT', 1),
    (30, 'Adição da denúncia', 1),
    (31, 'Aditamento', 1),
    (32, 'Administração Pública', 1),
    (33, 'Advocacia administrativa', 1),
    (34, 'Advogado dativo ou assistente judiciário', 1),
    (35, 'Advocacia-Geral da União', 1),
    (36, 'Agravo', 1),
    (37, 'Agravo de instrumento', 1),
    (38, 'Agravo retido', 1),
    (39, 'Ajuizar', 1),
    (40, 'Alvará de soltura', 1),
    (41, 'Amicus curiae', 1),
    (42, 'Anistia', 1),
    (43, 'Antecipação de tutela ou Tutela Antecipada', 1),
    (44, 'Anulação', 1),
    (45, 'Apelação ', 1);